name: alchemist
description: A web server built using the shelf package.
version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.0.0
  redis: ^2.0.0
  shelf: ^1.1.1
  shelf_router: ^1.1.1

